embedding_models:
  nomic-embed-text:
    dimensions: 768
    max_length: 8192

context_models:
  llama3.2:
    temperature: 0.1
    max_tokens: 4096
    top_p: 0.95
    presence_penalty: 0.0
    frequency_penalty: 0.0

query_models:
  mistral:
    temperature: 0.7
    max_tokens: 2048
    top_p: 0.95
    presence_penalty: 0.0
    frequency_penalty: 0.0
  
  deepseek-r1:8b:
    temperature: 0.7
    max_tokens: 16384
    top_p: 0.95
    presence_penalty: 0.0
    frequency_penalty: 0.0

  deepseek-r1:70b:
    temperature: 0.7
    max_tokens: 4096
    top_p: 0.95
    presence_penalty: 0.0
    frequency_penalty: 0.0
  
  gpt-3.5-turbo:
    temperature: 0.5
    max_tokens: 4096
    top_p: 0.95
    presence_penalty: 0.0
    frequency_penalty: 0.0

vector_db_settings:
  chromadb:
    distance_metric: cosine
    n_results: 5
  
  faiss:
    distance_metric: cosine
    n_results: 5
  
  qdrant:
    distance_metric: cosine
    n_results: 5
    collection_name: documents 